spring.application.name=code
spring.datasource.url=jdbc:postgresql://127.0.0.1:55432/wp2_project
spring.datasource.username=tristan
spring.datasource.password=1234

spring.data.redis.host=localhost
spring.data.redis.port=63797

spring.jpa.hibernate.ddl-auto=create
spring.cache.type=redis
spring.jpa.show-sql=true
